apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "windocks-sql-proxy.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}  
  template:
    metadata:
      labels:
        app: {{ template "windocks-sql-proxy.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: dotnetapp
          ports:
            - containerPort: {{ .Values.webapp.port }}
          env:
            - name: SQLSERVER_HOST
              value: {{ .Values.webapp.sqlserverHost }}
            - name: SQLSERVER_SA_PASSWORD
              value: {{ .Values.webapp.sqlserverPassword }}
